### ISSUE TITLE
Unable to reauth

### ISSUE THREAD

**Issue by chemelli74** [keatontaylor/custom_components#1391]
**Describe the bug**
When asked for reauth, I always get an error saying "your password is wrong" (or similar, translated from Italian).
Both password and OTP are correct.

**To Reproduce**
1. Confirm reauth prompt

**Expected behavior**
Be able to reauth when requested

**Screenshots**

**System details**
 - Home-assistant (version): 2021.10.5
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v3.10.10
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account): Yes

**Logs**

```
2021-10-20 08:30:01 WARNING (MainThread) [alexapy.helpers] alexaapi.send_announcement((<alexapy.alexaapi.AlexaAPI object at 0x7f13a13458e0>, 'Attenzione, la lavastoviglie è ancora in standby. Spegnila!'), {'customer_id': 'A39M4H7SQEH9PT'
, 'targets': ['5218ef6322b94cba806137a722f664d0'], 'title': 'Home Assistant', 'method': 'spoken', 'queue_delay': 1.5}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2021-10-20 08:30:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 144, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 922, in send_announcement
    await self.send_sequence(
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 144, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 476, in send_sequence
    await self.run_behavior(node_data, queue_delay=queue_delay)
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 144, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 398, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 202, in _post_request
    return await self._request("post", uri, data)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 172, in _request
    raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API
```

**Additional context**

**Comment by chemelli74** [comment]
Additional info:

![image](https://user-images.githubusercontent.com/57354320/138102103-1330385d-3dfe-40d5-9e70-1400ca523003.png)
