### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mihalski** [keatontaylor/custom_components#21]
I managed to get as far as successfully configuring the component but then it gets the below error which repeats approximately every 50 seconds.
```
018-08-08 18:27:45 DEBUG (SyncWorker_14) [custom_components.media_player.alexa] Using cookies to log in.
2018-08-08 18:27:47 DEBUG (SyncWorker_14) [custom_components.media_player.alexa] Logged in.
2018-08-08 18:27:47 DEBUG (SyncWorker_14) [custom_components.media_player.alexa] Log in successful with cookies
2018-08-08 18:27:47 DEBUG (SyncWorker_14) [custom_components.media_player.alexa] Setting up Alexa devices
2018-08-08 18:27:54 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/alexa.py", line 192, in setup_alexa
    update_devices()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 325, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 325, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/media_player/alexa.py", line 164, in update_devices
    update_devices, url)
  File "/config/custom_components/media_player/alexa.py", line 228, in __init__
    self.refresh(device)
  File "/config/custom_components/media_player/alexa.py", line 267, in refresh
    self._media_is_muted = self._session['volume']['muted']
TypeError: 'NoneType' object is not subscriptable
```
If there is any further info you require let me know.

Regards,
Michal

**Comment by mihalski** [comment]
I downloaded the current version and this is what I get now.
```

2018-08-14 17:47:17 DEBUG (SyncWorker_17) [custom_components.media_player.alexa] Log in successful with cookies
2018-08-14 17:47:17 DEBUG (SyncWorker_17) [custom_components.media_player.alexa] Setting up Alexa devices
2018-08-14 17:47:22 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/alexa.py", line 217, in setup_alexa
    update_devices()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 325, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 325, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/media_player/alexa.py", line 189, in update_devices
    update_devices, url)
  File "/config/custom_components/media_player/alexa.py", line 253, in __init__
    self.refresh(device)
  File "/config/custom_components/media_player/alexa.py", line 295, in refresh
    if 'muted' in self._session['volume']
TypeError: argument of type 'NoneType' is not iterable
2018-08-14 17:47:35 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/alexa.py", line 167, in <lambda>
    track_utc_time_change(hass, lambda now: update_devices(), second=30)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 325, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 325, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/media_player/alexa.py", line 189, in update_devices
    update_devices, url)
  File "/config/custom_components/media_player/alexa.py", line 253, in __init__
    self.refresh(device)
  File "/config/custom_components/media_player/alexa.py", line 295, in refresh
    if 'muted' in self._session['volume']
TypeError: argument of type 'NoneType' is not iterable
```

Always ready to test a new version :)
