### ISSUE TITLE
alexa.py throws exception after upgrade to HA 0.78.0

### ISSUE THREAD

**Issue by tlpbu** [keatontaylor/custom_components#42]
First I want to thank you for your hard work making alexa tts work in HA.

Just now I upgraded HA to version 0.78.0 and Alexa media_player is gone from dashboard I am now having exception in the logs:
```
2018-09-18 19:09:09 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform alexa
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/alexa.py", line 142, in setup_platform
    config.get(CONF_DEBUG))
  File "/config/custom_components/media_player/alexa.py", line 607, in __init__
    self.login_with_cookie()
  File "/config/custom_components/media_player/alexa.py", line 630, in login_with_cookie
    self.login(cookies=cookies)
  File "/config/custom_components/media_player/alexa.py", line 701, in login
    if (cookies is not None and self.test_loggedin(cookies)):
  File "/config/custom_components/media_player/alexa.py", line 673, in test_loggedin
    '/api/devices-v2/device')
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 644, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 644, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 192, in resolve_redirects
    proxies = self.rebuild_proxies(prepared_request, proxies)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 276, in rebuild_proxies
    environ_proxies = get_environ_proxies(url, no_proxy=no_proxy)
  File "/usr/local/lib/python3.6/site-packages/requests/utils.py", line 763, in get_environ_proxies
    return getproxies()
  File "/usr/local/lib/python3.6/urllib/request.py", line 2480, in getproxies_environment
    for name, value in os.environ.items():
  File "/usr/local/lib/python3.6/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'OPENBLAS_MAIN_FREE'
```

Could it be caused by breaking changes in Home Assistant or is it just unsuccessful upgrade that would require for me to clear something and authenticate again?

**Comment by tlpbu** [comment]
Exception is gone and media_player.alexa entity is available again in HA. Simple hassio restart helped - apparently HA does not always start up properly immediately after upgrade.
