### ISSUE TITLE
no longer showing devices

### ISSUE THREAD

**Issue by garywilson4** [keatontaylor/custom_components#54]
can anyone help please getting this error
```
2018-12-24 12:40:15 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform alexa
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/alexa.py", line 146, in setup_platform
    config.get(CONF_DEBUG))
  File "/config/custom_components/media_player/alexa.py", line 618, in __init__
    self.login_with_cookie()
  File "/config/custom_components/media_player/alexa.py", line 641, in login_with_cookie
    self.login(cookies=cookies)
  File "/config/custom_components/media_player/alexa.py", line 776, in login
    self._data = self.get_inputs(soup)
  File "/config/custom_components/media_player/alexa.py", line 654, in get_inputs
    for field in form.find_all('input'):
AttributeError: 'NoneType' object has no attribute 'find_all'
```
recently changed my password as i had an account compromised and now this won't work  i have changed the password in my !secrets file

**Comment by alandtse** [comment]
Delete the alexa_media.pickle file; it will reprompt you for any captchas.
