### ISSUE TITLE
Error introduced in v0.10.0

### ISSUE THREAD

**Issue by aaronwolen** [keatontaylor/custom_components#68]
I've been using this custom component very successfully for several months—Alexa TTS is so awesome. 

However, updating to v0.10.0 seems to have broken the component for me and HASS throws the following error:

```
2019-01-25 16:13:41 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/alexa.py", line 201, in <lambda>
    track_utc_time_change(hass, lambda now: update_devices(), second=30)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 315, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 315, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/media_player/alexa.py", line 235, in update_devices
    update_devices, url, authentication)
  File "/config/custom_components/media_player/alexa.py", line 318, in __init__
    self.refresh(device)
  File "/config/custom_components/media_player/alexa.py", line 358, in refresh
    self._last_called = self._get_last_called()
  File "/config/custom_components/media_player/alexa.py", line 448, in _get_last_called
    if self._device_serial_number == self.alexa_api.get_last_device_serial():
  File "/config/custom_components/media_player/alexa.py", line 1008, in get_last_device_serial
    if last_activity['activityStatus'](0) != 'DISCARDED_NON_DEVICE_DIRECTED_INTENT':
TypeError: 'str' object is not callable
```

**Comment by alandtse** [comment]
Thanks for the report.
@brianhanifin can you take a look?

**Comment by alandtse** [comment]
Nevermind @brianhanifin , I see the error and tested a fix.
