### ISSUE TITLE
Homeassistant.components.recorder value too long

### ISSUE THREAD

**Issue by hairychris** [keatontaylor/custom_components#94]
When you have quite a long email address we can't store history using the recorder.

````
homeassistant_1  | 2019-02-25 02:58:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (psycopg2.DataError) value too long for type character varying(32)
homeassistant_1  |  [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%(event_type)s, %(event_data)s, %(origin)s, %(time_fired)s, %(created)s, %(context_id)s, %(context_user_id)s) RETURNING events.event_id'] [parameters: {'event_type': 'alexa_media_tania.REDACTED@gmail.com', 'event_data': '{"last_called_change": {"serialNumber": "REDACTED", "timestamp": 1551045651091}}', 'origin': 'LOCAL', 'time_fired': datetime.datetime(2019, 2, 25, 2, 58, 18, 314834, tzinfo=<UTC>), 'created': datetime.datetime(2019, 2, 25, 2, 58, 39, 208746), 'context_id': 'REDACTED', 'context_user_id': None}] (Background on this error at: http://sqlalche.me/e/9h9h)
homeassistant_1  | Exception in thread Recorder:
homeassistant_1  | Traceback (most recent call last):
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
homeassistant_1  |     cursor, statement, parameters, context
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
homeassistant_1  |     cursor.execute(statement, parameters)
homeassistant_1  | psycopg2.DataError: value too long for type character varying(32)
homeassistant_1  |
homeassistant_1  |
homeassistant_1  | The above exception was the direct cause of the following exception:
homeassistant_1  |
homeassistant_1  | Traceback (most recent call last):
homeassistant_1  |   File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
homeassistant_1  |     self.run()
homeassistant_1  |   File "/usr/src/app/homeassistant/components/recorder/__init__.py", line 298, in run
homeassistant_1  |     session.flush()
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2436, in flush
homeassistant_1  |     self._flush(objects)
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2574, in _flush
homeassistant_1  |     transaction.rollback(_capture_exception=True)
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
homeassistant_1  |     compat.reraise(exc_type, exc_value, exc_tb)
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
homeassistant_1  |     raise value
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2534, in _flush
homeassistant_1  |     flush_context.execute()
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
homeassistant_1  |     rec.execute(self)
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
homeassistant_1  |     uow,
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
homeassistant_1  |     insert,
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1116, in _emit_insert_statements
homeassistant_1  |     statement, params
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
homeassistant_1  |     return meth(self, multiparams, params)
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
homeassistant_1  |     return connection._execute_clauseelement(self, multiparams, params)
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
homeassistant_1  |     distilled_params,
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
homeassistant_1  |     e, statement, parameters, cursor, context
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
homeassistant_1  |     util.raise_from_cause(sqlalchemy_exception, exc_info)
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
homeassistant_1  |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
homeassistant_1  |     raise value.with_traceback(tb)
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
homeassistant_1  |     cursor, statement, parameters, context
homeassistant_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
homeassistant_1  |     cursor.execute(statement, parameters)
homeassistant_1  | sqlalchemy.exc.DataError: (psycopg2.DataError) value too long for type character varying(32)
homeassistant_1  |  [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%(event_type)s, %(event_data)s, %(origin)s, %(time_fired)s, %(created)s, %(context_id)s, %(context_user_id)s) RETURNING events.event_id'] [parameters: {'event_type': 'alexa_media_tania.REDACTED@gmail.com', 'event_data': '{"last_called_change": {"serialNumber": "REDACTED", "timestamp": 1551045651091}}', 'origin': 'LOCAL', 'time_fired': datetime.datetime(2019, 2, 25, 2, 58, 18, 314834, tzinfo=<UTC>), 'created': datetime.datetime(2019, 2, 25, 2, 58, 39, 208746), 'context_id': 'REDACTED', 'context_user_id': None}] (Background on this error at: http://sqlalche.me/e/9h9h)
````

**Comment by hairychris** [comment]
Duplicate of https://github.com/keatontaylor/custom_components/issues/88
